name: Java CI with Gradle

on:
  push:
    branches: [ kotlin-rewrite ]
    paths-ignore:
      - "README.md"
      - "LICENSE.md"
      - ".gitignore"
      - ".gitattributes"
      - "/run"
      - ".github/*.yml"
  pull_request:
    branches: [ kotlin-rewrite ]
    paths-ignore:
      - "README.md"
      - "LICENSE.md"
      - ".gitignore"
      - ".gitattributes"
      - "/run"
      - ".github/*.yml"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Set up JDK 16
      uses: actions/setup-java@v2
      with:
        java-version: '16'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Setup and Build with Gradle
      run: ./gradlew setupCIWorkspace build --no-daemon
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        paths: |
          ./forge-1.8.9/build/libs
          ./fabric-1.17.1/build/libs
