name: Java CI with Gradle

on:
  push:
    branches: [ kotlin-rewrite ]
  pull_request:
    branches: [ kotlin-rewrite ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '16'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Setup Mod Workspaces
      run: ./gradlew setupCIWorkspace
    - name: Build with Gradle
      run: ./gradlew build
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        paths:
         - ./forge-1.8.9/build/libs
         - ./fabric-1.17.1/build/libs
